### ISSUE TITLE
AttributeError: 'Manager' object has no attribute 'within'

### ISSUE THREAD

**Issue by wallace57** [simonluijk/django-distance#1]
Hi @simonluijk 
I try your code and got issue, please follow bellow
myzip = Zip.objects.get(code="94129")
zips = Zip.objects.within(myzip.location, D(mi=50), D(mi=100)) => It return error "AttributeError: 'Manager' object has no attribute 'within'"
or
zips = myzip.within(D(mi=50), D(mi=100)) => It's work

I'm using django 1.6.5 ^ 1.7 still error.

**Comment by simonluijk** [comment]
Turns out that the issue is with the documentation. The distance manager is available through the Zip.distance attribute. I have corrected the read me in this commit https://github.com/simonluijk/django-distance/commit/eb553abdfdeca5efb9014933741efc7059018748

**Comment by wallace57** [comment]
Thanks @simonluijk :)
